### ISSUE TITLE
Doesn't support Halo 1 .Map Files

### ISSUE THREAD

**Issue by B1ueN0va** [CptWesley/RadiantMapToWavefrontObj#19]
This doesn't seem to support Halo 1 Map Files, Here's a download to the Blood Gulch .map file to confirm.

[bloodgulch.zip](https://github.com/CptWesley/RadiantMapToWavefrontObj/files/5121028/bloodgulch.zip)

**Comment by CptWesley** [comment]
Halo isn't based on the Quake engine, so the map format is just a completely different one and outside of the scope of this project unfortunately.
